"""add connector token_hash

Revision ID: a5aedf7515db
Revises: 3a6184cd0b32
Create Date: 2026-09-19 12:52:53.013978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5aedf7515db'
down_revision: Union[str, None] = '3a6184cd0b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connector_configs', sa.Column('token_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'connector_configs', ['token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connector_configs', type_='unique')
    op.drop_column('connector_configs', 'token_hash')
    # ### end Alembic commands ###
